[build]
  publish = "netlify-deploy"
  command = "./build.sh"

[build.environment]
  NODE_VERSION = "18.19.0"
  NETLIFY_BUILD_IMAGE = "focal"
  NODE_ENV = "production"
  DISABLE_YARN_INSTALL = "true"
  SKIP_YARN_INSTALL = "true"
  CI = "true"
  BUILD_IMAGE = "focal"
  UBUNTU_VERSION = "20.04"

[context.production.environment]
  NODE_VERSION = "18.19.0"
  NETLIFY_BUILD_IMAGE = "focal"

[context.deploy-preview.environment]
  NODE_VERSION = "18.19.0"
  NETLIFY_BUILD_IMAGE = "focal"

[context.branch-deploy.environment]
  NODE_VERSION = "18.19.0"
  NETLIFY_BUILD_IMAGE = "focal"
